FROM python:3.9-slim

WORKDIR /usr/src/app/backend

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# Expose the desired port (e.g., 8000)
EXPOSE 8001

# Command to run the start script
CMD ./start-celery-container.sh

# CMD celery -A backend worker --loglevel=DEBUG