version : '3.9'

services :
  db :  
    restart : always
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    ports :
      - 5432:5432
    environment :
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes : 
      - ./data:/var/lib/postgresql
 
  django :
    restart : always
    build : 
      context : .
      dockerfile: Dockerfile.django
    volumes : 
      - .:/usr/src/app/backend 
    depends_on:
      - db
    ports : 
      - 8000:8000 

  react :
    restart: always
    depends_on:
      - django
    build : 
      context : ../frontend
      target : development
    ports:
      - 3000:3000
    volumes : 
      - ../frontend:/usr/src/app/frontend 

  react_production:
    depends_on:
      - django
    build:
      context: ../frontend
      target: production
    ports:
      - 80:80

  redis :
    build : 
      context : .
      dockerfile: Dockerfile.redis
    ports: 
      - 6379:6379

  celery :
    build : 
      context : .
      dockerfile: Dockerfile.celery
    depends_on:
      - django
    ports: 
      - 8001:8001
      
  celery_beat : 
    build : 
      context : .
      dockerfile: Dockerfile.celery_beat
    depends_on:
      - celery
    ports: 
      - 8002:8002
