# Generated by Django 4.1.3 on 2023-03-04 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, unique=True)),
                ('poster', models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg')),
                ('ratings', models.JSONField()),
                ('released', models.DateField(max_length=256, null=True)),
                ('plot', models.TextField()),
                ('contentRate', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.IntegerField()),
                ('commentsNumber', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg')),
                ('trailer', models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg')),
                ('imdbId', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('thumbnail', models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='api.directors')),
                ('genre', models.ManyToManyField(to='api.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.movie')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
