# Generated by Django 4.1.3 on 2023-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='commentsNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
