# Generated by Django 4.1.3 on 2023-02-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_commentsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tailer',
            field=models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg'),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='https://imdb-api.com/images/128x176/nopicture.jpg'),
        ),
    ]
