# Generated by Django 4.2.13 on 2024-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=None, null=True),
        ),
    ]
