# Generated by Django 4.1.3 on 2023-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_image_movie_tailer_movie_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbId',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
