# Generated by Django 4.2.13 on 2024-05-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='commentsNumber',
        ),
    ]
