# Generated by Django 4.1.3 on 2023-02-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movie_imdbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tailer',
            new_name='trailer',
        ),
    ]
