# Generated by Django 4.2.13 on 2024-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_genre_movie_genres_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='contentRating',
            new_name='content_rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(default=None, null=True),
        ),
    ]
