# Generated by Django 4.2.13 on 2024-06-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movie_duration_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviesimilarity',
            unique_together={('movie_1', 'movie_2')},
        ),
    ]
