# Generated by Django 4.2.13 on 2024-05-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movie_commentsnumber'),
        ('comments', '0003_alter_reply_replying_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.movie'),
        ),
    ]
