# Generated by Django 4.1.3 on 2023-01-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='movie_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
        migrations.AddField(
            model_name='replies',
            name='movie_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
    ]
