# Generated by Django 4.1.3 on 2023-01-31 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_comments_movie_page_replies_movie_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replies',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
