# Generated by Django 4.1.3 on 2023-02-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_comments_profile_alter_replies_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='authentication/imgs/pfps'),
        ),
    ]
