# Generated by Django 5.0.6 on 2024-05-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_comments_date_alter_replies_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentslikesdislike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='commentslikesdislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='movie_page',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user_ld',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user_replying_to',
        ),
        migrations.RemoveField(
            model_name='replieslikesdislike',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replieslikesdislike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='CommentsLikesDislike',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.DeleteModel(
            name='RepliesLikesDislike',
        ),
    ]
