# Generated by Django 4.1.3 on 2023-02-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_commentslikesdislike_comments_user_ld'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepliesLikesDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='replies',
            name='user_ld',
            field=models.ManyToManyField(through='authentication.RepliesLikesDislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
